import Head from "next/head";
import { Inter } from "@next/font/google";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillInstagram,
  AiFillCalendar,
} from "react-icons/ai";
import { IoSchool } from "react-icons/io5";
import { MdHomeWork } from "react-icons/md";
import { TbArrowTopTail } from "react-icons/tb";
import Image from "next/image";
import cartoon_avatar from "../public/cartoon-avata.png";
import programming_language from "../public/programming-language.png";
import framework from "../public/framework.png";
import data_management from "../public/data-management.png";
import { useState, useRef, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkmode] = useState(false);

  // move ref
  const topPage = useRef(null);
  const moveToTop = useRef(null);
  const moveSkills = useRef(null);
  const moveQualification = useRef(null);
  const moveAbout = useRef(null);

  useEffect(() => {
    window.onscroll = function () {
      scrollFunction();
    };
  });

  function scrollFunction() {
    if (
      document.body.scrollTop > 500 ||
      document.documentElement.scrollTop > 500
    ) {
      moveToTop.current.className = "fixed right-4 bottom-4";
    } else {
      moveToTop.current.className = "hidden";
    }
  }

  // handle move
  const executeScroll = () =>
    topPage.current.scrollIntoView({ behavior: "smooth" });

  const handleMoveSkills = () =>
    moveSkills.current.scrollIntoView({ behavior: "smooth" });

  const handleMoveQualification = () =>
    moveQualification.current.scrollIntoView({ behavior: "smooth" });

  const handleMoveAbout = () =>
    moveAbout.current.scrollIntoView({ behavior: "smooth" });

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Hung Nguyen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-5 md:px-20 lg:px-40 dark:bg-gray-900">
        <section ref={topPage} className="min-h-screen">
          <button ref={moveToTop} className="hidden" onClick={executeScroll}>
            <TbArrowTopTail className="cursor-pointer text-3xl sm:text-4xl lg:text-5xl m-auto text-cyan-400" />
            <span className="text-cyan-400 text-sm sm:text-lg lg:text-xl">
              move to top
            </span>
          </button>
          <nav className="flex justify-between py-10">
            <h1 className="text-xl font-burtons dark:text-white">
              Hung Nguyen
            </h1>
            <ul className="flex items-center">
              <li>
                <button
                  className="text-black text-sx sm:text-xl font-medium pr-2 py-2 rounded-md ml-3 hover:text-cyan-500 dark:text-white dark:hover:text-cyan-500"
                  onClick={handleMoveSkills}
                >
                  Skills
                </button>
              </li>
              <li>
                <button
                  className="text-black text-sx sm:text-xl font-medium pr-2 py-2 rounded-md ml-3 hover:text-cyan-500 dark:text-white dark:hover:text-cyan-500"
                  onClick={handleMoveQualification}
                >
                  Qualification
                </button>
              </li>
              <li>
                <button
                  className="text-black text-sx sm:text-xl font-medium pr-4 py-2 rounded-md ml-3 hover:text-cyan-500 dark:text-white dark:hover:text-cyan-500"
                  onClick={handleMoveAbout}
                >
                  About
                </button>
              </li>
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkmode(!darkMode)}
                  className="cursor-pointer text-sx sm:text-xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-4 text-sx sm:text-xl"
                  href="https://drive.google.com/file/d/1_rpqXh9K8UnlmvX8sBHj8szS9DoyAmiy/view"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-5">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl lg:text-7xl">
              Hung Nguyen
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Web Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
              A person who is passionate about programming. Currently, my strong
              point is the client side processing, I am improving the server
              side knowledge to become better
            </p>
          </div>
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-5 overflow-hidden md:w-96 md:h-96">
            <Image className="pt-8" src={cartoon_avatar} alt="" />
          </div>
        </section>

        <section>
          <div ref={moveSkills} id="skills" className="text-center mt-10">
            <h3 className="text-3xl md:text-4xl lg:text-5xl pt-10 py-1 dark:text-white uppercase">
              Skills
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              My technical level
            </p>
          </div>
          <div className="md:flex mt-14 justify-around gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-400">
              <Image
                className="mx-auto"
                src={programming_language}
                alt=""
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Programming Languages
              </h3>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">ABAP</p>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">C++</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-400">
              <Image
                className="mx-auto"
                src={framework}
                alt=""
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Frameworks/Platforms
              </h3>
              <p className="text-gray-800 py-1">ReactJS</p>
              <p className="text-gray-800 py-1">NextJS</p>
              <p className="text-gray-800 py-1">SCSS</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
              <p className="text-gray-800 py-1">Tailwind CSS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-400">
              <Image
                className="mx-auto"
                src={data_management}
                alt=""
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Data Management Systems
              </h3>
              <p className="text-gray-800 py-1">MS SQL Server</p>
              <p className="text-gray-800 py-1">SAP</p>
            </div>
          </div>
        </section>
        <section>
          <div
            ref={moveQualification}
            id="qualification"
            className="text-center mt-16"
          >
            <h3 className="text-3xl md:text-4xl lg:text-5xl pt-10 py-1 dark:text-white uppercase">
              Qualification
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              My personal journey
            </p>
          </div>
          <div className="mt-28">
            <div className="grid grid-cols-[1fr,1fr] mb-6">
              <div className="text-3xl">
                <i className="flex justify-center items-center gap-2  dark:text-white">
                  <IoSchool />
                  Education
                </i>
              </div>
              <div className="text-3xl">
                <i className="flex justify-center items-center gap-2  dark:text-white">
                  <MdHomeWork />
                  Work
                </i>
              </div>
            </div>

            <div className="mt-14">
              <div>
                <div className="grid grid-cols-[1fr,max-content,1fr] gap-y-6">
                  <div className="text-center">
                    <h3 className="text-xl font-bold  dark:text-white">
                      Computer Science
                    </h3>
                    <p className="text-gray-600  dark:text-white">
                      Ho Chi Minh City Open University
                    </p>
                    <div className="">
                      <i className="flex justify-center items-center gap-1 text-gray-600  dark:text-white">
                        <AiFillCalendar /> 2017 - 2021
                      </i>
                    </div>
                  </div>
                  {/* <div className="inline-block w-3 h-3 bg-black rounded-full mt-2"></div> */}
                  <div className="mx-1">
                    <span className="inline-block w-3 h-3 bg-black rounded-full mt-2 dark:bg-white"></span>
                    <span className="block w-px h-full bg-black translate-x-1.5 -translate-y-2 dark:bg-white"></span>
                  </div>
                </div>
                {/* <div className="grid grid-cols-[1fr,max-content,1fr] gap-y-6">
                  <div></div>
                  <div>
                    <span></span>
                    <span></span>
                  </div>
                  <div className="text-center">
                    <h3>Computer Science</h3>
                    <p>Open University</p>
                    <div>
                      <i className="flex justify-center items-center gap-1">
                        <AiFillCalendar /> 2017 - 2021
                      </i>
                    </div>
                  </div>
                </div>
                <div className="learn grid grid-cols-[1fr,max-content,1fr] gap-y-6">
                  <div>
                    <h3>Computer Science</h3>
                    <p>Open University</p>
                    <div>
                      <i className="flex items-center gap-1">
                        <AiFillCalendar /> 2017 - 2021
                      </i>
                    </div>
                  </div>
                </div> */}
                <div className="work grid grid-cols-[1fr,max-content,1fr] gap-y-6">
                  <div></div>
                  <div className="mx-1">
                    <span className="inline-block w-3 h-3 bg-black rounded-full mt-2 dark:bg-white"></span>
                    <span></span>
                  </div>
                  <div className="text-center">
                    <h3 className="text-xl font-bold dark:text-white">
                      SAP ABAP Developer
                    </h3>
                    <p className="text-gray-600 dark:text-white">
                      FPT Information System
                    </p>
                    <div>
                      <i className="flex justify-center items-center gap-1 text-gray-600 dark:text-white">
                        <AiFillCalendar /> 2021 - 2022
                      </i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div ref={moveAbout} id="about" className="text-center mt-56">
            <h3 className="text-3xl md:text-4xl lg:text-5xl pt-10 py-1 dark:text-white uppercase">
              About
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Get in touch
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 pt-24 py-3 text-gray-600">
            <a href="https://www.linkedin.com/in/hung-nguyen-9b31b925b">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/HungNguyen31">
              <AiFillGithub />
            </a>
            <a href="https://www.instagram.com/huwng_31">
              <AiFillInstagram />
            </a>
          </div>
        </section>
        <section className="h-80"></section>
      </main>
    </div>
  );
}
